config/routes.rb
Rails.application.routes.draw do
  resources :images

  resources :machine_sets do 
    resources :machines
  end

  get 'machines/new_form', to: 'machines#new_form'

  devise_for :users

  root to: 'static_pages#home'

  get 'admin', to: 'admin#index'
  post 'admin/update_signup_status', to: 'admin#update_signup_status'

  namespace 'about_my_machines' do
    get 'show'
    get 'edit'
    post 'update'
  end

  namespace 'instagram' do
    get 'edit_user'
    post 'search_user'
    post 'update_user'
    get 'edit_tags'
    post 'update_tags'
    get 'images/:user_id', to: '#get_images'
    get 'remove_images'
  end

  delete 'instagram/:image_id', to: 'instagram#destroy'

end

app/models/machine_set.rb
class MachineSet < ActiveRecord::Base
  validates :price, presence: true
  validates :title, presence: true
  validates :quantity, presence: true
  has_many :machines, dependent: :destroy

end

app/controllers/machine_sets_controller.rb
class MachineSetsController < ApplicationController
  before_action :set_machine_set, only: [:show, :edit, :update, :destroy]

  before_action :authenticated_admin?, except: [:index]

  # GET /machine_sets
  # GET /machine_sets.json
  def index
    @machine_sets = MachineSet.all
  end

  # GET /machine_sets/1
  # GET /machine_sets/1.json
  def show
  end

  # GET /machine_sets/new
  def new
    @machine_set = MachineSet.new
    @machine = Machine.new
    @machines = [Machine.new]
    @counter = session[:machine_counter] ? session[:machine_counter] : 0
  end

  # GET /machine_sets/1/edit
  def edit
    @machines = @machine_set.machines
    @counter = session[:machine_counter] ? session[:machine_counter] : 0
    @machine = Machine.new
  end

  # POST /machine_sets
  # POST /machine_sets.json
  def create
    @machine_set = MachineSet.new(machine_set_params)
    respond_to do |format|
      binding.pry
      if @machine_set.save
        machines = []
        params['machine_set']['machines'].keys.each do |key|
          param_holder = params['machine_set']['machines'][key]
          param_holder['machine_set_id'] = @machine_set.id
          machines.push(param_holder)
        end
        if Machine.save_all(machines)
          format.html { redirect_to @machine_set, notice: 'Machine set was successfully created.' }
          format.json { render :show, status: :created, location: @machine_set }
        else
          @machine = Machine.new
          format.html { render :new }
          format.json { render json: @machine_set.errors, status: :unprocessable_entity }
        end
      else
        @machine = Machine.new
        format.html { render :new }
        format.json { render json: @machine_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_sets/1
  # PATCH/PUT /machine_sets/1.json
  def update
    respond_to do |format|
      if @machine_set.update(machine_set_params)
        format.html { redirect_to @machine_set, notice: 'Machine set was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine_set }
      else
        format.html { render :edit }
        format.json { render json: @machine_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_sets/1
  # DELETE /machine_sets/1.json
  def destroy
    @machine_set.destroy
    respond_to do |format|
      format.html { redirect_to machine_sets_url, notice: 'Machine set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine_set
      @machine_set = MachineSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_set_params
      params.require(:machine_set).permit(:title, :description, :price, :quantity, :image_url)
    end
end

app/helpers/machine_sets_helper.rb
module MachineSetsHelper
end

app/views/machine_sets/_form.html.haml
= form_for @machine_set, :html => { :multipart => true } do |f|
  - if @machine_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(@machine_set.errors.count, "error")} prohibited this machine_set from being saved:"
      %ul
        - @machine_set.errors.full_messages.each do |msg|
          %li= msg

  - if @machine.errors.any?
    #error_explanation
      %h2= "#{pluralize(@machine.errors.count, "error")} prohibited this machine from being saved:"
      %ul
        - @machine.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .row
      .col-md-9
        = f.label :title
        %small required
        = f.text_field :title, class: 'form-control', :placeholder => "Title for entire set"
      .col-md-3
        = f.label :price
        %small required
        .input-group
          .input-group-addon $
          = f.text_field :price, class: 'form-control', :placeholder => "Amount"
  .form-group
    .row
      .col-md-9
        = f.label :description
        = f.text_area :description, class: 'form-control', :placeholder => "Description for entire set"
      .col-md-3
        = f.label :quantity
        %small required
        = f.number_field :quantity, class: 'form-control', :value => 1
  .form-group
    .row
      .col-md-12
        - @machines.each do |machine|
          = render partial: 'machines/form', locals: { machine: machine }
          - @counter += 1
  = f.button 'Add New Machine', class: 'btn btn-info add-machine pull-right', type: 'button'
  .form-group
    = f.submit 'Save', class: 'btn btn-default'

app/views/machine_sets/edit.html.haml
.row
  .col-md-10.col-md-offset-1.main-container
    %h1.text-center Edit Set

    = render 'form'

    = link_to 'Show', @machine_set
    \|
    = link_to 'Back', machine_sets_path

app/views/machine_sets/index.html.haml
.row
  .col-md-10.col-md-offset-1.main-container
    %h1.text-center Listing Sets

    %table
      %thead
        %tr
          %th Title
          %th Description
          %th Price
          %th Quantity
          %th Image url
          %th
          %th
          %th

      %tbody
        - @machine_sets.each do |machine_set|
          %tr
            %td= machine_set.title
            %td= machine_set.description
            %td= machine_set.price
            %td= machine_set.quantity
            %td= machine_set.image_url
            %td= link_to 'Show', machine_set
            %td= link_to 'Edit', edit_machine_set_path(machine_set)
            %td= link_to 'Destroy', machine_set, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Machine set', new_machine_set_path

app/views/machine_sets/new.html.haml
.row
  .col-md-10.col-md-offset-1.main-container
    %h1.text-center New Set

    = render 'form'

    = link_to 'Back', machine_sets_path

app/views/machine_sets/show.html.haml
.row
  .col-md-10.col-md-offset-1.main-container
    %p#notice= notice
    - binding.pry
    %p
      %b Title:
      = @machine_set.title
    %p
      %b Description:
      = @machine_set.description
    %p
      %b Price:
      = @machine_set.price
    %p
      %b Quantity:
      = @machine_set.quantity
    %p
      %b Image url:
      = @machine_set.image_url

    = link_to 'Edit', edit_machine_set_path(@machine_set)
    \|
    = link_to 'Back', machine_sets_path