config/routes.rb
Rails.application.routes.draw do
  resources :images

  resources :machine_sets do 
    resources :machines
  end

  get 'machines/new_form', to: 'machines#new_form'

  devise_for :users

  root to: 'static_pages#home'

  get 'admin', to: 'admin#index'
  post 'admin/update_signup_status', to: 'admin#update_signup_status'

  namespace 'about_my_machines' do
    get 'show'
    get 'edit'
    post 'update'
  end

  namespace 'instagram' do
    get 'edit_user'
    post 'search_user'
    post 'update_user'
    get 'edit_tags'
    post 'update_tags'
    get 'images/:user_id', to: '#get_images'
    get 'remove_images'
  end

  delete 'instagram/:image_id', to: 'instagram#destroy'

end

app/models/instagram.rb
class Instagram < ActiveRecord::Base

  def images
    tags = RedisModel.tags
    tags = tags.split(',') unless tags.class == Array || tags == nil || tags.empty?
    tags.collect!(&:downcase) unless tags == nil
    @image_array = []
    if tags
      Instagram.all.each do |image|
        if (image['image_tags'].split(',').collect!(&:downcase) & tags).count > 0
          @image_array.push image
        end
      end
    end
    return @image_array
  end

  def standard_resolution_width
    return self.standard_resolution_size.split(',')[0]
  end

  def standard_resolution_height
    return self.standard_resolution_size.split(',')[1]
  end

  def reload_images
    Instagram.delete_all
    image_scrape
  end

  def update_images
    image_scrape
  end

  private

  def image_scrape
    return unless RedisModel.user_id != nil
    instagram_images_url = $GET_CLIENT_IMAGES
    instagram_images_url = instagram_images_url.sub("[USER ID]",RedisModel.user_id)

    most_recent_instgram_image = Instagram.order(created_time: :desc).first if Instagram.count > 0
    latest_time = most_recent_instgram_image == nil ? nil : most_recent_instgram_image.created_time
    latest_time = DateTime.now - 20.years if latest_time == nil
    latest_id = most_recent_instgram_image == nil ? nil : most_recent_instgram_image.image_id

    begin
      result = Net::HTTP.get(URI.parse(instagram_images_url))
      result_hash = JSON.parse(result)
      if (result_hash['meta']['code'] == 200)
        result_hash['data'].each do |result|
          i = get_image_hash(result)
          return if i['created_time'] < latest_time  || i['image_id'] == latest_id
          instagram = Instagram.new i
          instagram.save
        end
      end
      puts result_hash['pagination']
      if result_hash['pagination'] && result_hash['pagination']['next_url']
        instagram_images_url = result_hash['pagination']['next_url']
      end
    end while result_hash['pagination'] && result_hash['pagination']['next_url']
  end

  def get_image_hash(image_hash)
    image = {}
    image['image_tags'] = image_hash['tags'].join(',')
    image['created_time'] = DateTime.strptime(image_hash['created_time'],'%s')
    image['image_id'] = image_hash['id']
    image['instagram_link'] = image_hash['link']
    image['low_resolution_url'] = image_hash['images']['low_resolution']['url']
    image['low_resolution_size'] = image_hash['images']['low_resolution']['width'].to_s + ',' + image_hash['images']['low_resolution']['height'].to_s
    image['thumbnail_url'] = image_hash['images']['thumbnail']['url']
    image['thumbnail_size'] = image_hash['images']['thumbnail']['width'].to_s + ',' + image_hash['images']['thumbnail']['height'].to_s
    image['standard_resolution_url'] = image_hash['images']['standard_resolution']['url']
    image['standard_resolution_size'] = image_hash['images']['standard_resolution']['width'].to_s + ',' + image_hash['images']['standard_resolution']['height'].to_s
    image['caption'] = image_hash['caption'] != nil ? image_hash['caption']['text'] : nil
    return image
  end

  def get_file_value(file_line)
    return nil unless file_line
    return file_line.split(':').last.strip
  end

  def contact_params
    params.require(:contact).permit(:tags, :created_time, :instagram_link, :low_resolution_url, :thumbnail_url, :standard_reolution_url, :caption, :thumbnail_size, :low_resolution_size, :standard_size)
  end
end

app/controllers/instagram_controller.rb
require 'net/http'

class InstagramController < ApplicationController
  before_action :authenticated_admin?
  def edit_user
    @instagram_user = RedisModel.user_name
  end

  def search_user
    get_clients_url = $GET_CLIENTS
    get_clients_url = get_clients_url.sub("[USERNAME]",params[:user_name])
    
    result = Net::HTTP.get(URI.parse(get_clients_url))
    result_hash = JSON.parse(result)

    @results = []
    if (result_hash["meta"]["code"] == 200)
      @results = result_hash["data"]
    end
  end

  def remove_images
    instagram = Instagram.new
    @instagram_images = instagram.images
  end

  def update_user
    # instagram = Instagram.new.read_file
    params.slice('user_name', 'user_id').keys.each do |key|
      temp_hash = {}
      temp_hash['key'] = key
      temp_hash['value'] = params[key]
      RedisModel.update_value key, params[key]
    end

    Instagram.new.reload_images
    redirect_to admin_path
  end

  def edit_tags
    @instagram_tags_array = []
    if RedisModel.tags
      @instagram_tags = RedisModel.tags
      @instagram_tags.join(',') if @instagram_tags.class != String
      @instagram_tags_array = @instagram_tags.split(',')
      @instagram_tags_array = [] if @instagram_tags_array == nil
    end
    @instagram_possible_tags = Instagram.all.pluck(:image_tags).delete_if(&:empty?).collect{ |x| x.split(',')}.flatten.uniq!.sort if Instagram.all.count > 0
  end

  def update_tags
    # instagram = Instagram.new.read_file
    # instagram.tags = params["tags"]
    params.slice('tags').keys.each do |key|
      RedisModel.update_value key, params[key].split(',').collect{ |x| x.strip}.collect(&:downcase).join(',')
    end
    redirect_to admin_path
  end

  def destroy
    if params[:image_id]
      image = Instagram.find_by_id(params[:image_id])
      respond_to do |format|
        if image.destroy
          format.html { head 200, content_type: "text/html" }
          format.json { head :ok }
        else
          format.html { head 404, content_type: "text/html" }
          format.json { render :json => image.errors, :status => :unprocessable_entity }
        end
      end
    end
  end
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/views/instagram/_tag_helper.html.haml
- first = tag_array.include?(tag) ? '' : 'none'
%a{:href => "#", class: "instagram-tags-minus #{tag}-tag", :style=>"display:#{first};", data: { tag_name: "#{tag}" }}
  %span.glyphicon.glyphicon-minus{"aria-hidden" => "true", "style" => "color:red"}
- second = tag_array.include?(tag) ? 'none' : ''  
%a{:href => "#", class: "instagram-tags-add #{tag}-tag", :style=>"display:#{second};", data: { tag_name: "#{tag}" }}
  %span.glyphicon.glyphicon-plus{"aria-hidden" => "true", "style" => "color:green"}
= tag

app/views/instagram/edit_tags.html.haml
.row
  .col-md-10.col-md-offset-1.main-container
    %h1.text-center Edit Instagram Tags
    Type in the tags you want to scrape off instagram. Seperate the tags with commas. Leave empty to get image with no tags.
    %br
    %br
    = form_tag("#{instagram_update_tags_path}", html: {class: "form"}) do
      .form-group
        %input{:name => "tags", :type => "text", class: 'form-control', :value => @instagram_tags, :id => 'instagram-tags'}
      .form-group
        %input{:type => "submit", :value => "Update Instagram Tags", class: 'btn'}
    %br
    %h3.text-center Current Instagram Tags
    - @instagram_possible_tags.each_slice(3) do |tags|
      .row
        .col-md-4
          = render partial: 'tag_helper', locals: { tag: tags[0], tag_array: @instagram_tags_array }
        .col-md-4
          = render partial: 'tag_helper', locals: { tag: tags[1], tag_array: @instagram_tags_array }
        .col-md-4
          = render partial: 'tag_helper', locals: { tag: tags[2], tag_array: @instagram_tags_array }

app/views/instagram/edit_user.html.haml
.row
  .col-md-6.col-md-offset-3.main-container
    %h1.text-center Edit Instagram User
    Type the user name in the box and click the button. I will show the list of possible users and you will select the user you want to show images for.
    %br
    %br
    = form_tag("#{instagram_search_user_path}", html: {class: "form"}) do
      .form-group
        %input{:name => "user_name", :type => "text", :value => "#{@instagram_user}", class: 'form-control'}
      .form-group
        %input{:type => "submit", :value => "Find Instagram User", class: 'btn btn-blue'}

app/views/instagram/remove_images.html.haml
.row.instagram-remove-images-row
  - @instagram_images.each do |image|
    .col-md-4{id: "image-#{image.id}"}
      = image_tag(image.low_resolution_url, class: "img-responsive main-images")
      %button.btn.btn-danger.center-block.instagram-remove-image{:type => "button", data: {image_id: "#{image.id}"}} Remove Image

app/views/instagram/search_user.html.haml
.row
  .col-md-8.col-md-offset-2.main-container
    %h1.text-center Search Instagram Users
    Searching for users like 
    = params["user_name"]
    - @results.each do |result|
      .row
        = form_tag("#{instagram_update_user_path}", html: {class: "form"}) do
          %input{:name => "user_name", :type => "hidden", :value => params["user_name"]}
          %input{:name => "user_id", :type => "hidden", :value => result["id"]}
          .col-md-3
            = image_tag(result["profile_picture"], class: 'img-circle')
          .col-md-3
            = result["username"]
          .col-md-3
            - if result["full_name"].length > 0
              = result["full_name"]
            - else
              &nbsp;
          .col-md-3
          %input{:type => "submit", :value => "Select user", class: 'btn btn-blue confirm'}
      %br

app/views/instagram/view_user.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container
    %h1.text-center Current Instagram User
    %h4
      = @instagram.user
    = link_to 'Change Instagram User', instagram_edit_user_path