config/routes.rb
Rails.application.routes.draw do
  resources :images

  resources :machine_sets do 
    resources :machines
  end

  get 'machines/new_form', to: 'machines#new_form'

  devise_for :users

  root to: 'static_pages#home'

  get 'admin', to: 'admin#index'
  post 'admin/update_signup_status', to: 'admin#update_signup_status'

  namespace 'about_my_machines' do
    get 'show'
    get 'edit'
    post 'update'
  end

  namespace 'instagram' do
    get 'edit_user'
    post 'search_user'
    post 'update_user'
    get 'edit_tags'
    post 'update_tags'
    get 'images/:user_id', to: '#get_images'
    get 'remove_images'
  end

  delete 'instagram/:image_id', to: 'instagram#destroy'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :machine_sets
  has_many :images

  def self.save_all(machines)
    return_value = true
    machines.each do |machine|

      new_machine = Machine.new
      new_machine.title = machine['title']
      new_machine.description = machine['description']
      new_machine.machine_set_id = machine['machine_set_id']
      if new_machine.title.length > 0 && new_machine.save

        machine['images'].each do |image|
          uploaded_file = Cloudinary::Uploader.upload(image.tempfile.path)
          new_image = Image.new
          new_image.public_id = uploaded_file['public_id']
          new_image.width = uploaded_file['width']
          new_image.height = uploaded_file['height']
          new_image.format = uploaded_file['format']
          new_image.bytes = uploaded_file['bytes']
          new_image.url = uploaded_file['url']
          new_image.secure_url = uploaded_file['secure_url']

          new_image.machine_id = new_machine.id

          if !new_image.save
            return false
          end
        end

      end

      return return_value

    end
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  
  before_action :authenticated_admin?

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  def new_form
    @machine = Machine.new
    @counter = (session[:machine_counter] ? session[:machine_counter] = session[:machine_counter] + 1 : session[:machine_counter] = 0)
    respond_to do |format|
      format.html { render partial: 'panel', locals: {machine: @machine, counter: @counter} }
    end
  end

  # GET /machines/new
  def new
    @counter = (session[:machine_counter] ? session[:machine_counter] = session[:machine_counter] + 1 : session[:machine_counter] = 0)
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
    @counter = (session[:machine_counter] ? session[:machine_counter] = session[:machine_counter] + 1 : session[:machine_counter] = 0)
  end

  # POST /machines
  # POST /machines.json
  def create
    session.delete(:machine_counter)
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        session.delete(:machine_counter)
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:title, :description, :machine_set_id, :images)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.haml
#accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  =render partial: "machines/panel", locals: {machine: machine, counter: @counter}            

#imageModal.modal.fade{"aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-custom-size
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
      .modal-body{ :style => "" }
        %img.img-custom-responsive.img-responsive{:alt => "Machine Image", :src => "", :class => "modal-image", :style => ""}

app/views/machines/_panel.html.haml
.panel.panel-default
  .panel-heading{:role => "tab"}
    %h4.panel-title
      %a.collapsed{"aria-controls" => "#{counter}", "aria-expanded" => "false", "data-parent" => "", "data-toggle" => "collapse", :href => "##{counter}", :role => "button", :class => "new-machine-title"}
        = machine.title == nil ? 'New Machine' : machine.title
      %a.css_btn_class.pull-right.machine-remove{:href => "#", data: { id: machine.id }}
        %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
  .panel-collapse.collapse.in{"aria-labelledby" => "#{counter}", :role => "tabpanel", :id => "#{counter}"}
    .panel-body
      .form-group
        .row
          .col-md-12
            = label_tag :title
            %small required to be saved
            = text_field_tag "machine_set[machines][#{counter}][title]", machine.title , class: 'form-control machine-title', :placeholder => "Title for machine"
      .form-group
        .row
          .col-md-12
            = label_tag :description
            = text_area_tag "machine_set[machines][#{counter}][description]", machine.description, class: 'form-control machine-description', :placeholder => "Description for machine"
      .form-group
        .row
          .col-md-12
            = label_tag :images
            = file_field("machine_set[machines][#{counter}]",:images, accept: 'image/png,image/jpeg,image/jpg', class: 'btn machine-images', :multiple => true  )
      - machine.images.each do |image|
        .image-row
          = render partial: "images/form", locals: { image: image }

app/views/machines/edit.html.haml
%h1 Editing machine

= render 'form'

= link_to 'Show', @machine
\|
= link_to 'Back', machines_path

app/views/machines/index.html.haml
%h1 Listing machines

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Machine set
      %th
      %th
      %th

  %tbody
    - @machines.each do |machine|
      %tr
        %td= machine.title
        %td= machine.description
        %td= machine.machine_set_id
        %td= link_to 'Show', machine
        %td= link_to 'Edit', edit_machine_path(machine)
        %td= link_to 'Destroy', machine, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Machine', new_machine_path

app/views/machines/new.html.haml
%h1 New machine

= render 'form'

= link_to 'Back', machines_path

app/views/machines/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @machine.title
%p
  %b Description:
  = @machine.description
%p
  %b Machine set:
  = @machine.machine_set_id

= link_to 'Edit', edit_machine_path(@machine)
\|
= link_to 'Back', machines_path